### ISSUE TITLE
No Download after it was done

### ISSUE THREAD

**Issue by Zubinexu** [dreamingtulpa/midjourney-archive-chrome-extension#1]
![Screenshot 2023-05-11 160620](https://github.com/dreamingtulpa/midjourney-archive-chrome-extension/assets/20671178/89080498-3d2d-48b9-b6f2-4b04c1610f8f)

Issue may be 6000 files created in one day .

Nothing happened after it was done , no downloads , so maybe split download for bigger batches in 2- 3 ? or 1000 files ?

**Comment by dreamingtulpa** [comment]
Can you put together a PR?

On May 11, 2023, GitHub ***@***.***> wrote:
>

> Nothing happened after it was done , no downloads , so maybe split
> download for bigger batches in 2- 3 ? or 1000k files ?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/dreamingtulpa/midjourney-archive-chrome-
extension/issues/1>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/A3S5IFI2SZ5RUOOUR5NGWVTXFTQMXANCNFSM6AAAAAAX6D7O4U>.
You are receiving this because you are subscribed to this thread.Message
ID: <dreamingtulpa/midjourney-archive-chrome-
***@***.***>

**Comment by Zubinexu** [comment]
I have no idea , how to do that.
I have tried smaller batches up to 1k files and works ok 

But .. it has no use to me since :
- filename is not the same as MJ , no one is going to do a visual search for 1-2 files inside a batch of 1k-3k files . Search data done by using prompt characteristics is faster.
-  cannot use it for bigger batches downloads

**Comment by dreamingtulpa** [comment]
Implemented a Bulk option to avoid this issue.
